# Generated by Django 2.1 on 2019-06-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35, verbose_name='用户名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('uphone', models.IntegerField(max_length=11, null=True, verbose_name='手机号')),
            ],
            options={
                'db_table': 'UserInfo',
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
    ]
